- name: Create docker_nginx directory
  file:
    path: "{{ user.home }}/docker/docker_nginx"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "{{ user.home }}/docker/docker_nginx/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create etc directories
  file:
    path: "{{ user.home }}/docker/docker_nginx/etc/nginx/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy nginx.conf
  template:
    src: ./etc/nginx/nginx.conf.j2
    dest: "{{ user.home }}/docker/docker_nginx/etc/nginx/nginx.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550